version: '3'

networks:
  benchmark:
    driver: bridge

services:
  mongodb:
    image: mongo
    container_name: mongo-benchmark
    environment: 
    - MONGO_INITDB_ROOT_USERNAME=benchmark
    - MONGO_INITDB_ROOT_PASSWORD=benchmark
    volumes:
      - .docker/mongodb/data:/data/db
    ports:
      - '27018:27017'
    command: mongoimport -db benchmark --collection messages --type json --file packages/messages.json --jsonArray
    networks:
      - benchmark
 redis:
    image: redis
    container_name: redis-benchmark
    command: redis-server --requirepass benchmark
    ports:
      - '6379:6379'
    networks:
      - benchmark
  in-process-server:
    container_name: in-process-server
    build:
      context: ./packages/in-process-server
    environment: 
      - API_PORT=8000
      - MONGO_URI=mongodb://benchmark:benchmark@mongodb/playground?authSource=admin
      - MAX_CACHE_SIZE=1000
      - LOG_LEVEL=all
    depends_on: 
      - mongodb
    networks:
      - benchmark
  redis-server:
    container_name: redis-server
    build:
      context: ./packages/redis-server
    environment: 
      - API_PORT=8001
      - MONGO_URI=mongodb://benchmark:benchmark@mongodb/playground?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=benchmark
      - LOG_LEVEL=all
    depends_on: 
      - redis
      - mongodb
    networks:
      - benchmark
